#!/usr/bin/env bash

set -euo pipefail

# One-command deterministic release flow:
# 1) Generate CHANGES.md from staged changes
# 2) Extract concise CHANGE_SUMMARY
# 3) Validate summary quality
# 4) Run release with summary
# 5) Remove CHANGES.md

./run_generate_changes.sh

CHANGE_SUMMARY="$(./run_extract_change_summary.sh | tr -d '\r')"

if [[ -z "${CHANGE_SUMMARY// }" ]]; then
  echo "Error: extracted CHANGE_SUMMARY is empty." >&2
  exit 1
fi

word_count="$(echo "$CHANGE_SUMMARY" | awk '{print NF}')"
if [[ "$word_count" -lt 8 ]]; then
  echo "Error: extracted CHANGE_SUMMARY is too short (${word_count} words)." >&2
  echo "Summary: $CHANGE_SUMMARY" >&2
  exit 1
fi

if echo "$CHANGE_SUMMARY" | grep -Eiq 'manual summary|script failure|placeholder|not generated by script'; then
  echo "Error: extracted CHANGE_SUMMARY looks like a fallback/placeholder." >&2
  echo "Summary: $CHANGE_SUMMARY" >&2
  exit 1
fi

./run_release.sh --summary "$CHANGE_SUMMARY"
rm -f CHANGES.md

echo "Release flow completed via run_release_from_changes.sh"
