#!/usr/bin/env bash

set -euo pipefail

# Deterministically generate CHANGE_SUMMARY and a CHANGES.md artifact
# from the staged diff of the current repository.
#
# Usage:
#   ./run_generate_changes.sh

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# Stage the release candidate first, per release rules.
git add -A :/
# Exclude generated output artifact from staged summary inputs.
git restore --staged CHANGES.md >/dev/null 2>&1 || true

STATUS_LINES="$(git diff --cached --name-status)"
FILE_LINES="$(git diff --cached --name-only)"

if [[ -z "$FILE_LINES" ]]; then
  cat > CHANGES.md <<'EOF'
# CHANGES

## CHANGE_SUMMARY

Not generated by script. Derive this summary from STAGED_FILE_STATUS and STAGED_DIFF.

## STAGED_FILE_STATUS

```text
(none)
```

## STAGED_FILES

```text
(none)
```

## STAGED_DIFF

```diff
(none)
```
EOF

  echo "CHANGES.md generated. CHANGE_SUMMARY was intentionally not generated by script."
  exit 0
fi

DIFF_CONTENT="$(git diff --cached)"

{
  cat <<'EOF'
# CHANGES

## CHANGE_SUMMARY

Not generated by script. Derive this summary from STAGED_FILE_STATUS and STAGED_DIFF.

EOF
  cat <<'EOF'
## STAGED_FILE_STATUS

```text
EOF
  printf '%s\n' "$STATUS_LINES"
  cat <<'EOF'
```

## STAGED_FILES

```text
EOF
  printf '%s\n' "$FILE_LINES"
  cat <<'EOF'
```

## STAGED_DIFF

```diff
EOF
  printf '%s\n' "$DIFF_CONTENT"
  cat <<'EOF'
```
EOF
} > CHANGES.md

# Keep CHANGES.md as generated output, not part of the staged release set by default.
git restore --staged CHANGES.md >/dev/null 2>&1 || true

echo "CHANGES.md generated."
echo "CHANGE_SUMMARY was intentionally not generated by script."
